version: '3.9'
services:
  openlistmedia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openlistmedia
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./media_wall.db:/app/media_wall.db
      - ./media_wall_site/data:/app/media_wall_site/data
    restart: unless-stopped
