version: '3.9'
services:
  openlistmedia:
    image: ghcr.io/yancj9ya/openlistmedia:latest
    container_name: openlistmedia
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yml
      - ./data:/app/data
      - ./data/cache:/app/.cache
    restart: unless-stopped
